<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
<?php /* @var $block \Amit\Orderpage\Block\Success */?>
<?php //echo __('Custom template file content.'); ?>
<?php //echo $block->getSomething(); ?>

 <?php
  // get order-id (the EntityId) ###
 
  $merchants = $block->getMerchants();

  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

  $orderId        = $block->getOrderId();
  $order          = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($orderId);
  $subtotal       = $order->getSubtotal();
  $discount       = $order->getDiscountAmount(); 
  $affiliateTotal = ($subtotal + $discount);
  $merchantID     = $block->getMerchant();

  //foreach($merchants as $merchantID)
  //{
    //$merchantID     ="66031"; // Production
    //$merchantID     ="27453"; // Dev / Pre-Production
  ?>
    <img src="https://shareasale.com/sale.cfm?tracking=<?php echo $orderId; ?>&amount=<?php echo $affiliateTotal; ?>&transtype=sale&merchantID=<?php echo $merchantID ?>" width="1" height="1">
  <?php
  //}